apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pos-api
  template:
    metadata:
      labels:
        app: pos-api
    spec:
      containers:
        - name: pos-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          env:
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: MONGO_URL
              value: "{{ .Values.env.MONGO_URL }}"
