apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pos-api
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.ingress.hosts[0].host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pos-api
                port:
                  number: 3000
